language: go

go:
- 1.2.x
- 1.3.x
- 1.4.x
- 1.5.x
- 1.6.x
- 1.7.x
- 1.8.x
- master

matrix:
  allow_failures:
  - go: master

script:
- ./go.test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
